### ISSUE TITLE
What do you think?

### ISSUE THREAD

**Issue by dazinator** [dazinator/Csla.Orleans#1]
@tfreitasleal - noticed you forked my repo recently? I am just curios to know if you have had a chance to have a look and what you think? This is purely experimental at this stage but I am considering it as a potential scale out approach for CSLA should the need arise in the future.

**Comment by tfreitasleal** [comment]
Hi,
I'm interested in Orleans as I think this might be an important technology in the future.
I noticed it was just experimental and I forked it so I remember to check out the progress.
